###
### macro definitions
###
###

### compile for OS
OS = VEOS

### Fortran compiler related macros
F90 = nfort
F90LINKER = nfort
FOPTIONS = -fextend-source


### C compiler related macros
CC = ncc
COPTIONS =


### C linker related macros
LDOPTIONS =
AR = nar rv
RANLIB = nar -ts


### MPI related macros
MPI_HOME = ${NMPI_ROOT}
MPI_F90 = mpinfort
MPI_INC = -I$(MPI_HOME)/include
MPI_LIBS =
# eof
