C      INCLUDE FILE FOR GENERAL FILE VER-1.1
C
      INTEGER*4 ANY, INQUIR, OPEN, ASCII, UNFMT, BINARY, NEWSET, CLOSE
      PARAMETER ( ANY    = -1 )
      PARAMETER ( INQUIR =  0 )
      PARAMETER ( OPEN   =  1 )
      PARAMETER ( ASCII  =  1 )
      PARAMETER ( UNFMT  =  2 )
      PARAMETER ( BINARY =  3 )
      PARAMETER ( NEWSET =  4 )
      PARAMETER ( CLOSE  =  5 )
C
      INTEGER*4 INTARY, FLTARY, DBLARY
      PARAMETER ( INTARY =  6 ) 
      PARAMETER ( FLTARY =  7 ) 
      PARAMETER ( DBLARY =  8 ) 
C
      INTEGER*4 MAXMOD
      PARAMETER ( MAXMOD = 3 )
      CHARACTER*8 FLMODE(MAXMOD)
C
      DATA FLMODE( ASCII  ) / 'ASCII   ' /
      DATA FLMODE( UNFMT  ) / 'UNFORMAT' /
      DATA FLMODE( BINARY ) / 'BINARY  ' /
C
      INTEGER*4 MAXTYP
      PARAMETER ( MAXTYP = 8 )
      CHARACTER*8 HEADER(MAXTYP)
C
      DATA HEADER( ASCII  ) / '#A_GF_V1' /
      DATA HEADER( UNFMT  ) / '#U_GF_V1' /
      DATA HEADER( BINARY ) / '#B_GF_V1' /
      DATA HEADER( NEWSET ) / '#NEW_SET' /
      DATA HEADER( CLOSE  ) / '#ENDFILE' /
C
      DATA HEADER( INTARY ) / '#INT_ARY' /
      DATA HEADER( FLTARY ) / '#FLT_ARY' /
      DATA HEADER( DBLARY ) / '#DBL_ARY' /
C
      INTEGER*4 ARY0D, ARY1D, ARY2D
      PARAMETER ( ARY0D = 0 ) 
      PARAMETER ( ARY1D = 1 ) 
      PARAMETER ( ARY2D = 2 ) 
C
      INTEGER*4 HEAD, DATA, END, UNKNWN
      PARAMETER ( UNKNWN = 0 ) 
      PARAMETER ( HEAD   = 1 ) 
      PARAMETER ( DATA   = 2 ) 
      PARAMETER ( END    = 3 ) 
C
      INTEGER*4 NONE, SELECT, ALL, GIVE
      PARAMETER ( NONE    = 0 ) 
      PARAMETER ( SELECT  = 1 ) 
      PARAMETER ( ALL     = 2 ) 
      PARAMETER ( GIVE    = 3 ) 
C
      INTEGER*4 EXIT
      PARAMETER ( EXIT    = 999 ) 
C
CCCCCCCCC--CCYYMOD.030305----
CC      CHARACTER*4  FMTAS / '(A8)' /
CC      CHARACTER*5  FMTAN / '(A30)' /
CC      CHARACTER*5  FMTAM / '(A60)' /
CC      CHARACTER*6  FMTI  / '(6I12)' /
CC      CHARACTER*12 FMTF  / '(5(1PE14.6))' /
CC      CHARACTER*13 FMTD  / '(5(1PE22.14))' /
C
      CHARACTER*4  FMTAS 
      CHARACTER*5  FMTAN 
      CHARACTER*5  FMTAM 
      CHARACTER*6  FMTI  
      CHARACTER*12 FMTF  
      CHARACTER*13 FMTD  
C
      DATA FMTAS / "(A8)" /
      DATA FMTAN / '(A30)' /
      DATA FMTAM / '(A60)' /
      DATA FMTI  / '(6I12)' /
      DATA FMTF  / '(5(1PE14.6))' /
      DATA FMTD  / '(5(1PE22.14))' /
CCCCCCCCC--CCYYMOD.030305----
C
C      END OF INCLUDE FILE FOR GENERAL FILE VER-1.1
